language: node_js

# 2*2 matrix for tests
os:
  - linux
  - windows
node_js:
  - 10
  - 12

jobs:
  include:
    # run tests in Node.js stable and publish code coverage
    - name: 'Coverage'
      os: linux
      node_js: stable
      script:
        - npm run test-unit
        - npm run codecov -- -c -Z -f .coverage/coverage-final.json -F unit

    # create a new release if $CREATE_RELEASE is set
    - stage: Create Release
      if: env(CREATE_RELEASE) = true AND type = api AND tag IS blank
      os: osx
      node_js: 12
      git:
        depth: false # disable --depth
      script:
        # fail-fast using set -e
        - set -e
        # decrypt and ssh-add the deploy-key
        - openssl aes-256-cbc -K $encrypted_05f822b6caa8_key -iv $encrypted_05f822b6caa8_iv
          -in .github/travis-deploy-key.enc -out /tmp/travis-deploy-key -d
        - chmod 600 /tmp/travis-deploy-key
        - eval "$(ssh-agent -s)"
        - ssh-add /tmp/travis-deploy-key
        - rm /tmp/travis-deploy-key
        # convert remote URL from HTTPS to SSH
        - git remote set-url origin $(git config --get remote.origin.url | sed -E 's#(http.*://)([^/]+)/(.+)$#git@\2:\3#g')
        - ssh-keyscan github.com >> ~/.ssh/known_hosts
        # create release
        - npm run release $PUSH_TO_ORIGIN $PRERELEASE_SUFFIX
        - set +e

    # publish npm package on tagged builds
    - stage: Publish Package
      if: tag IS present
      os: linux
      node_js: 12
      git:
        depth: false # disable --depth
      script:
        # fail-fast using set -e
        - set -e
        # get prerelease suffix from version tag
        - TAG=$(echo $TRAVIS_TAG | sed 's/^.*-\([a-z]*\).*$/\1/')
        # set to `latest` in case of no suffix
        - TAG=$([ "${TAG}" = "$TRAVIS_TAG" ] && echo "latest" || echo $TAG)
        # make sure `latest` tag is create from main branch
        - '[ "$TAG" = "latest" ] && [ $(git rev-parse HEAD) != $(git rev-parse origin/main) ] && return 1 || return 0'
        - set +e
      deploy:
        edge: true # opt in to dpl v2
        provider: npm
        tag: $TAG
        on:
          tags: true
          all_branches: true

before_install:
  - '[[ -z "$CREATE_RELEASE" ]] && unset encrypted_05f822b6caa8_key || true'
  - '[[ -z "$CREATE_RELEASE" ]] && unset encrypted_05f822b6caa8_iv || true'
  - '[[ -z "$TRAVIS_TAG" ]] && unset NPM_API_TOKEN || true'

notifications:
  slack:
    secure: PuYBCkRXgUKxoFMyTZdYcxplpgW+T/hxq54gsFOcAxN079i7PTD/GmGIgKM1RviCocvroUst5bW3ULk3haYUb8gQSCyAeHzRl00DaoOXshTRjFzJyU6m5wbT/R45dh6ZO2BT6uwlVU95KznieCC+yjlbppPOis8bwxra08ODnsA1L7OeI7fVlKjyh+lPA4qnmuYpNtMfTO5mmHroHBS5nWoB1WctWuZQGSfDYLUr/XrhKkJOBbv7FI7setTroIRF4Rs9nIFEF3mzTuUK5VV6lQAZRzNHKmgD9DmGVeaB5Y4fWEznocV1d6cInsjMr4EyMYziyOFnnPZAk8GZapMDwD0/5E9L5+Q8uXhFhVHYurpZnP+wylqZmnfb4UaFcP96BBaavhfF/ai+LWlLbHiL5b1HX4dlauNfHdq1W1YCILI2Atfr+36rqu3102S6HHkOssoTw09ftLfQHuF6CNYnVE5cS40pupwFZj3o0h9yQnCFDPxlq2ls+hon+PKL9wCHL5MlG+jQZDDL8eZC8F9CoZUyVIxNhoh0fnZ+t4bIlGW5eB8f8oMCxcnjocxZpichfAsmuaPh/e2KfdoF/B7ce6+Tb3/YXqo5QVTsJ1Vzi4I7c3jx1Q0DAyZODsBKyE0y7NfmeVNap0WIgajiJBoKji8Fjw+tDfa3hSb4yyPSG6w=
  webhooks:
    urls:
      secure: GTWyny+NiqjXBd3lzcgOgq0H3LsI3NP7IUK0uFcz88AUdeSVVW1+nq81uzuFvl8BYqs8T95l7DvltyLQMxsWYCUHVg0WqOKNMgxMAjYZN+lfvdpohY1cpMNbcTt/jf8zl6SOdJ5wvj8wRXhEiPp9TyUfXKYHxS64bHTnVPsWeT271AuZCAePiOgY4xyYWYJ8SM1gqjHhjqbYUieer1acIzYKGAprayNewNI3P0HKA4AB3p8YEV3wwLhM2F0nsaEXIF37irmYjIKFLoAKmrmVHdeQqptBLf6E7Ovn3bzhXVNzusns4JLAIjKyg76u32NoGc4V7fuUaRjJs5ciWBEnmG+1/NNhygztGv9t0ODOmQRozv0yV+IuDKhROCP2gEbIFleM3CrXiYQdW0fwQSvSt2OB/Vcfujv7pEKrFvcZN8cs32Ll6RDjAfSTs3InuVmWrQDUMoALitvvUtoZn5oD1oxaGrJIiBilYfv70jKCZ44pJxFpWur1lHEm/xUmamo1c+5+nwkaMsJ7bsgXSyYOp/75nrffC2WJ1b/s4CM05YToqqnO5EkaBBgJJAqr8UgAipH74I/1GwNJB66gOl9fFwDWeEWEGEDYojlvAExzE8MvMQ9QFbp28n75jT5Oaap1D0VBv2n/CXYB4eDVQrT4J88s2WOYAdlNqFRt5meo3wY=
